
package net.javaci.ws.jaxws.sample1.client.soap.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SalutationEndpointService", targetNamespace = "http://server.sample1.jaxws.ws.javaci.net/", wsdlLocation = "file:/C:/Source/ECLIPSEWS/_TEMP/JavaKursuWs/JavaKursuWsJaxWsClient/src/main/resources/salutation.xml")
public class SalutationEndpointService
    extends Service
{

    private final static URL SALUTATIONENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALUTATIONENDPOINTSERVICE_EXCEPTION;
    private final static QName SALUTATIONENDPOINTSERVICE_QNAME = new QName("http://server.sample1.jaxws.ws.javaci.net/", "SalutationEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Source/ECLIPSEWS/_TEMP/JavaKursuWs/JavaKursuWsJaxWsClient/src/main/resources/salutation.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALUTATIONENDPOINTSERVICE_WSDL_LOCATION = url;
        SALUTATIONENDPOINTSERVICE_EXCEPTION = e;
    }

    public SalutationEndpointService() {
        super(__getWsdlLocation(), SALUTATIONENDPOINTSERVICE_QNAME);
    }

    public SalutationEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALUTATIONENDPOINTSERVICE_QNAME, features);
    }

    public SalutationEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SALUTATIONENDPOINTSERVICE_QNAME);
    }

    public SalutationEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALUTATIONENDPOINTSERVICE_QNAME, features);
    }

    public SalutationEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalutationEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SalutationEndpoint
     */
    @WebEndpoint(name = "SalutationEndpointPort")
    public SalutationEndpoint getSalutationEndpointPort() {
        return super.getPort(new QName("http://server.sample1.jaxws.ws.javaci.net/", "SalutationEndpointPort"), SalutationEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns SalutationEndpoint
     */
    @WebEndpoint(name = "SalutationEndpointPort")
    public SalutationEndpoint getSalutationEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.sample1.jaxws.ws.javaci.net/", "SalutationEndpointPort"), SalutationEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALUTATIONENDPOINTSERVICE_EXCEPTION!= null) {
            throw SALUTATIONENDPOINTSERVICE_EXCEPTION;
        }
        return SALUTATIONENDPOINTSERVICE_WSDL_LOCATION;
    }

}
