
package net.javaci.ws.jaxws.sample1.client.soap.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SalutationEndpoint", targetNamespace = "http://server.sample1.jaxws.ws.javaci.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SalutationEndpoint {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIt", targetNamespace = "http://server.sample1.jaxws.ws.javaci.net/", className = "net.javaci.ws.jaxws.sample1.client.soap.stubs.GetIt")
    @ResponseWrapper(localName = "getItResponse", targetNamespace = "http://server.sample1.jaxws.ws.javaci.net/", className = "net.javaci.ws.jaxws.sample1.client.soap.stubs.GetItResponse")
    @Action(input = "http://server.sample1.jaxws.ws.javaci.net/SalutationEndpoint/getItRequest", output = "http://server.sample1.jaxws.ws.javaci.net/SalutationEndpoint/getItResponse")
    public String getIt();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns net.javaci.ws.jaxws.sample1.client.soap.stubs.SalutationResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "salute", targetNamespace = "http://server.sample1.jaxws.ws.javaci.net/", className = "net.javaci.ws.jaxws.sample1.client.soap.stubs.Salute")
    @ResponseWrapper(localName = "saluteResponse", targetNamespace = "http://server.sample1.jaxws.ws.javaci.net/", className = "net.javaci.ws.jaxws.sample1.client.soap.stubs.SaluteResponse")
    @Action(input = "http://server.sample1.jaxws.ws.javaci.net/SalutationEndpoint/saluteRequest", output = "http://server.sample1.jaxws.ws.javaci.net/SalutationEndpoint/saluteResponse")
    public SalutationResponse salute(
        @WebParam(name = "arg0", targetNamespace = "")
        SalutationRequest arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
